# Generated by Django 4.0.3 on 2022-04-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_type',
            field=models.CharField(choices=[('Ka', 'Kakao'), ('Go', 'Google')], default='Ka', max_length=2),
        ),
    ]
