# Generated by Django 4.0.3 on 2022-03-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_status_notification_is_readed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_readed',
            new_name='is_read',
        ),
    ]
